export const API_CALL = 'API_CALL';
export const API_CALL_PAGINATION = 'API_CALL_PAGINATION';
export const SET_CONTACTS = 'SET_CONTACTS';
export const SET_CONTACTS_PAGINATION = 'SET_CONTACTS_PAGINATION';